import Head from "next/head";
import Link from "next/link";
import CircleTexture from "~/components/CircleTexture";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sign up | UI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="absolute right-[-12rem] top-[-12rem]">
          <CircleTexture />
        </div>

        <div></div>

        <div className="absolute bottom-[-20rem] left-[-20rem]">
          <CircleTexture />
        </div>
      </main>
    </>
  );
}
